const source = @import("source.zig");

pub const Kind = enum {
    kw_fn,
    kw_let,
    kw_mut,
    kw_struct,
    kw_enum,
    kw_match,
    kw_if,
    kw_else,
    kw_while,
    kw_true,
    kw_false,
    kw_and,
    kw_or,
    kw_not,
    kw_return,
    kw_trait,
    kw_impl,
    kw_for,
    kw_self,
    ident,
    int,
    string,
    l_paren,
    r_paren,
    l_brace,
    r_brace,
    comma,
    colon,
    equals,
    plus,
    minus,
    star,
    slash,
    percent,
    arrow,
    fat_arrow,
    eq_eq,
    bang_eq,
    lt,
    gt,
    le,
    ge,
    dot,
    semicolon,
    ampersand,
    question,
    l_bracket,
    r_bracket,
    newline,
    eof,
    invalid,

    pub fn describe(k: Kind) []const u8 {
        return switch (k) {
            .kw_fn => "`fn`",
            .kw_let => "`let`",
            .kw_mut => "`mut`",
            .kw_struct => "`struct`",
            .kw_enum => "`enum`",
            .kw_match => "`match`",
            .kw_if => "`if`",
            .kw_else => "`else`",
            .kw_while => "`while`",
            .kw_true => "`true`",
            .kw_false => "`false`",
            .kw_and => "`and`",
            .kw_or => "`or`",
            .kw_not => "`not`",
            .kw_return => "`return`",
            .kw_trait => "`trait`",
            .kw_impl => "`impl`",
            .kw_for => "`for`",
            .kw_self => "`self`",
            .ident => "an identifier",
            .int => "an integer literal",
            .string => "a string literal",
            .l_paren => "`(`",
            .r_paren => "`)`",
            .l_brace => "`{`",
            .r_brace => "`}`",
            .comma => "`,`",
            .colon => "`:`",
            .equals => "`=`",
            .plus => "`+`",
            .minus => "`-`",
            .star => "`*`",
            .slash => "`/`",
            .percent => "`%`",
            .arrow => "`->`",
            .fat_arrow => "`=>`",
            .eq_eq => "`==`",
            .bang_eq => "`!=`",
            .lt => "`<`",
            .gt => "`>`",
            .le => "`<=`",
            .ge => "`>=`",
            .dot => "`.`",
            .semicolon => "`;`",
            .ampersand => "`&`",
            .question => "`?`",
            .l_bracket => "`[`",
            .r_bracket => "`]`",
            .newline => "a line break",
            .eof => "end of file",
            .invalid => "an invalid token",
        };
    }
};

pub const Token = struct {
    kind: Kind,
    span: source.Span,
    value: []const u8 = &.{},
};
